export const THEME = {
  accent: {
    text: "text-red-500",
    textHover: "hover:text-red-500",
    bg: "bg-red-500",
    bgHover: "hover:bg-red-600",
    border: "border-red-300",
    lightBg: "bg-red-100",
    lightText: "text-red-600",
  },
  secondary: {
    text: "text-blue-500",
    textHover: "hover:text-blue-600",
    bg: "bg-blue-500",
    bgHover: "hover:bg-blue-600",
    border: "border-blue-300",
    lightBg: "bg-blue-50",
  },
  dark: {
    bg: "bg-slate-900",
    nav: "bg-slate-900/80",
    text: "text-slate-100",
    textSub: "text-slate-400",
    card: "bg-slate-800",
    border: "border-slate-700",
    input: "bg-slate-700",
    inputBorder: "border-slate-600",
    inputText: "text-white",
    footer: "bg-slate-900 border-slate-800",
  },
  light: {
    bg: "bg-stone-50",
    nav: "bg-white/80",
    text: "text-stone-800",
    textSub: "text-stone-600",
    card: "bg-white",
    border: "border-stone-200",
    input: "bg-white",
    inputBorder: "border-stone-300",
    inputText: "text-black",
    footer: "bg-stone-100 border-stone-200",
  },
};
